// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace SiTagAPI_1._0.Models;

public partial class animal
{
    [Key]
    public int id { get; set; }

    [Required]
    [StringLength(45)]
    [Unicode(false)]
    public string number { get; set; }

    public byte sex { get; set; }

    [Required]
    [StringLength(45)]
    [Unicode(false)]
    public string race { get; set; }

    [Required]
    [StringLength(45)]
    [Unicode(false)]
    public string specie { get; set; }

    [Required]
    [StringLength(45)]
    [Unicode(false)]
    public string color { get; set; }

    [Column(TypeName = "date")]
    public DateTime birthdate { get; set; }

    [InverseProperty("animal")]
    [JsonIgnore]
    public virtual ICollection<data> data { get; set; } = new List<data>();

    [InverseProperty("animal")]
    [JsonIgnore]
    public virtual ICollection<service> service { get; set; } = new List<service>();
}