// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SiTagAPI_1._0.Models;

public partial class division
{
    [Key]
    public int id { get; set; }

    public int farmId { get; set; }

    [Required]
    [StringLength(45)]
    [Unicode(false)]
    public string name { get; set; }

    [InverseProperty("division")]
    public virtual ICollection<data> data { get; set; } = new List<data>();

    [ForeignKey("farmId")]
    [InverseProperty("division")]
    public virtual farm farm { get; set; }
}