// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SiTagAPI_1._0.Models;

public partial class farm
{
    [Key]
    public int id { get; set; }

    [Required]
    [StringLength(45)]
    [Unicode(false)]
    public string name { get; set; }

    [Required]
    [StringLength(45)]
    [Unicode(false)]
    public string location { get; set; }

    public int userId { get; set; }

    [Required]
    [StringLength(45)]
    [Unicode(false)]
    public string description { get; set; }

    [InverseProperty("farm")]
    public virtual ICollection<division> division { get; set; } = new List<division>();

    [ForeignKey("userId")]
    [InverseProperty("farm")]
    public virtual user user { get; set; }
}