// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SiTagAPI_1._0.Models;

public partial class record
{
    [Key]
    public int id { get; set; }

    public int userId { get; set; }

    [Required]
    [StringLength(45)]
    [Unicode(false)]
    public string category { get; set; }

    public double amount { get; set; }

    [Column(TypeName = "date")]
    public DateTime date { get; set; }

    [Column("for")]
    public int _for { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string description { get; set; }

    [ForeignKey("userId")]
    [InverseProperty("record")]
    public virtual user user { get; set; }
}