// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SiTagAPI_1._0.Models;

public partial class user
{
    [Key]
    public int id { get; set; }

    [Required]
    [StringLength(45)]
    [Unicode(false)]
    public string name { get; set; }

    [Required]
    [StringLength(45)]
    [Unicode(false)]
    public string lastName { get; set; }

    [Required]
    [StringLength(45)]
    [Unicode(false)]
    public string email { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string password { get; set; }

    [Required]
    [StringLength(45)]
    [Unicode(false)]
    public string cellphone { get; set; }

    [InverseProperty("user")]
    public virtual ICollection<farm> farm { get; set; } = new List<farm>();

    [InverseProperty("user")]
    public virtual ICollection<record> record { get; set; } = new List<record>();
}